#!/usr/bin/env python3
  
from PIL import Image

im = Image.open("bla.png")

print(im.format, im.size, im.mode)

data = im.getdata()
w = im.width
h = im.height

x = 0
y = 0

for pixel in data:
    r, g, b, a = pixel
    print("PX %d %d %s%s%s%s" % (x, y, hex(r)[2:], hex(g)[2:], hex(b)[2:], hex(a)[2:]))
    x += 1
    if x == w:
        x = 0
        y += 1