#!/usr/bin/env python
import sys

import logging

from ncclient import manager


def connect(host, port, username, password):
    conn = manager.connect(host=host,
                           port=port,
                           username=username,
                           password=password,
                           timeout=60,
                           device_params={'name': 'junos'},
                           hostkey_verify=False)

    logging.info('show chassis cluster status')
    logging.info('*' * 30)
    result = conn.rpc("<command format=\"json\">show chassis cluster status</command>")
    logging.info(result)


if __name__ == '__main__':
    LOG_FORMAT = '%(asctime)s %(levelname)s %(filename)s:%(lineno)d %(message)s'
    logging.basicConfig(stream=sys.stdout, level=logging.INFO, format=LOG_FORMAT)

    host = "an-vsrx-01.ansible.eng.rdu2.redhat.com"
    username = "ansible"
    password = "Ansible"
    port = 830
    connect(host=host, port=port, username=username, password=password)