#!/bin/bash
# Search duplicate files
# Author: Vitaliy Skorobagatko <info@zoom.net.ua>
#################################################

FILEDUB_TMP="/tmp/filedup.hash"

echo " ___  _  _         _           "
echo "|  _||_|| | ___  _| | _ _  ___ "
echo "|  _|| || || -_|| . || | || . |"
echo "|_|  |_||_||___||___||___||  _|"
echo "                          |_|  "
echo -n "Search path: "
read path

# Search files in MD5 hashes and collects in the file
find "$path" -noleaf -type f -exec md5 -r {} \; | sed 's/ /:/' > $FILEDUB_TMP

# Showing hashes with duplicate files
sort $FILEDUB_TMP | cut -f1 -d ':' | uniq -d | while read hash;
do
  file=`cat $FILEDUB_TMP | grep $hash | cut -f2 -d ':'`
  echo $hash
  echo "--------------------------------"
  echo "$file"
  echo "--------------------------------"
done

# Cleaning
rm $FILEDUB_TMP